### ISSUE TITLE
Demo website failing to load, trying to resolve older version.

### ISSUE THREAD

**Issue by akadouri** [kamzek/deck.gl-particle#1]
Looks like the demo website wasn't updated when the repo was, it's failing to resolve `https://unpkg.com/deck.gl-particle@1.0.2/dist/deck.gl-particle.min.js`

Will have to settle for sharing the shiny [twitter](https://twitter.com/KamzekViz/status/1400451786314375173) gif for now 🙂

**Comment by zakjan** [comment]
Ah, I forgot to bump the version in the demo 🤦‍♂️ It's fixed now, thanks!
